### ISSUE TITLE
Release on flathub

### ISSUE THREAD

**Issue by ket0x4** [heret0x0/Mushroom#18]
People can download and use the program without compiling if you relese on flathub
https://github.com/flathub/flathub/wiki/App-Submission
https://flathub.org/home

**Comment by heret0x0** [comment]
Thanks for your contribution

This is somewhat planned but I was intending to postpone it for a while because I am still not sure of the app's stability
In the event that I do not find a report of performance problems among the current few users within some days, I will do so

and btw u can still install the app without compiling it from [here](https://github.com/azab246/Mushroom/releases/tag/v0.1)

**Comment by ket0x4** [comment]
Installed and works fine. Thanks
